apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "cluster-autoscaler.labels" . | nindent 4 }}
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
  name: cluster-autoscaler
  namespace: kube-system