apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  profile: default # https://istio.io/latest/docs/setup/additional-setup/config-profiles/
  values:
    global:
      defaultNodeSelector:
        nodegroup: istio
    gateways:
      istio-ingressgateway:
        type: NodePort
  addonComponents:
    grafana:
      enabled: true
      k8s:
        replicaCount: 1
    istiocoredns:
      enabled: false
    tracing:
      enabled: true
    kiali:
      enabled: true
      k8s:
        replicaCount: 1
    prometheus:
      enabled: true
      k8s:
        replicaCount: 1
  components:
    egressGateways:
      - enabled: false
    ingressGateways:
      - enabled: true
        k8s:
          service:
            ports:
              - name: status-port
                port: 15020
                targetPort: 15020
                nodePort: {{ required "A valid .Values.ingressGatewayHealthStatusNodePort entry required!" .Values.ingressGatewayHealthStatusNodePort }}
              - name: http2
                port: 80
                targetPort: 8080
                nodePort: {{ required "A valid .Values.ingressGatewayNodePort entry required!" .Values.ingressGatewayNodePort }}
              - name: https
                port: 443
                targetPort: 8443
                nodePort: 30302
              - name: tcp
                port: 31400
                targetPort: 31400
                nodePort: 30303
              - name: tls
                port: 15443
                targetPort: 15443
                nodePort: 30304


  # https://archive.istio.io/v1.4/docs/reference/config/installation-options/#gateways-options
